stages:
  - test


test:
  stage: test
  image: thecodingmachine/php:7.1-v1-cli

  script:
    - composer install --no-interaction --no-suggest
    - vendor/bin/phpstan analyse
    - vendor/bin/tester tests/unit
